---
- name: Install postgresql-server
  ansible.builtin.package:
    name: postgresql-server
    state: present

- name: Run postgresql setup
  shell: postgresql-setup --initdb

- name: Enabling and starting postgresql services
  service:
    name: postgresql
    state: started
    enabled: yes
