---
- name: Install postgresql-server
  ansible.builtin.package:
    name: postgresql-server
    state: present

- name: Run postgresql setup
  shell: 
    cmd: postgresql-setup --initdb
    creates: /var/lib/pgsql/data/postgresql.conf


- name: Enabling and starting postgresql services
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create user {{ ansible_ssh_user }} for postgresql
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ ansible_ssh_user }}"
    role_attr_flags: SUPERUSER
    state: present

- name: Create a new database with name {{ ansible_ssh_user }}
  become: true
  become_user: "{{ ansible_ssh_user }}"
  postgresql_db:
    name: "{{ ansible_ssh_user }}"
    login_user: "{{ ansible_ssh_user }}"
