---
- name: Install postgresql
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles: 
    - role: python_install
      tags: python_install
    - role: postgres_install
      tags: postgres_install
    - role: seven_databases_book
      tags: seven_databases_book
