---
- name: Install python and dependent packages
  package:
    name: 
      - python3
      - python3-pip
      - python3-devel
      - postgresql-devel
    state: latest

- name: Install psycopg2 used for postgresql_user
  pip: 
    name: psycopg2
    
